services:
  - type: web
    name: study-analyzer
    env: python
    pythonVersion: "3.13" # Matches your environment
    buildCommand: apt-get update && apt-get install -y tesseract-ocr poppler-utils && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata
