services:
  - type: web
    name: study-analyzer
    env: python
    buildCommand: apt-get update && apt-get install -y tesseract-ocr poppler-utils && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    autoDeploy: true
